version: '3.9'

services:
  app:
    build: 
      context: .
    restart: always

    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
volumes:
  postgres-data: